### ISSUE TITLE
ModuleNotFoundError: No module named 'src.optim'

### ISSUE THREAD

**Issue by NewEricWang** [SarthakYadav/fsd50k-pytorch#2]
hi, when I run "python train_fsd50k_chunks.py --cfg_file ./cfgs/densenet121_chunks_melspec.cfg -e ./works/densenet121_chunks_melspec_v1 --epochs 100", an error arises as follows "ModuleNotFoundError: No module named 'src.optim'".

**Comment by SarthakYadav** [comment]
Hi!

Sorry for responding so late! I just fixed this issue in the latest commit: https://github.com/SarthakYadav/fsd50k-pytorch/commit/86f143d918d3fcac0970679f2883385b5498ae63

Can you please try now?
